import Head from 'next/head';
import Image from 'next/image';
import { useState } from 'react';
import ModalExample from '../components/Modals/ModalExample';
import styles from '../styles/Home.module.scss';

export default function Home() {
  const [modalOpen, setModalOpen] = useState(false);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1
        className="text-uppercase text-red-500"
        onClick={() => setModalOpen(true)}
      >
        BASIC TEMPLATE
      </h1>

      <ModalExample
        closeModal={() => setModalOpen(false)}
        modalOpen={modalOpen}
      />
    </div>
  );
}
